# Generated by Django 5.2.15 on 2026-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lead_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddocument',
            name='cheque_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/cheque/'),
        ),
        migrations.AlterField(
            model_name='leaddocument',
            name='gst_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/gst/'),
        ),
        migrations.AlterField(
            model_name='leaddocument',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
