# Generated by Django 5.2.15 on 2026-07-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_repair_organization_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepagepermission',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('TL', 'Team Lead'), ('BDM', 'BDM'), ('Ops', 'Office Ops')], db_index=True, max_length=20),
        ),
    ]
